# -*- coding: utf-8 -*-
# =============================================================================
# Hugo Links Unit Tests
# =============================================================================
#
# Testing links using the famous "Les Misérables" network example.
#
from collections import defaultdict
from test.test_cases import TraphTestCase

PAGES = [
    's:http|h:com|h:myriel|',
    's:http|h:com|h:napoleon|',
    's:http|h:com|h:mllebaptistine|',
    's:http|h:com|h:mmemagloire|',
    's:http|h:com|h:countessdelo|',
    's:http|h:com|h:geborand|',
    's:http|h:com|h:champtercier|',
    's:http|h:com|h:cravatte|',
    's:http|h:com|h:count|',
    's:http|h:com|h:oldman|',
    's:http|h:com|h:labarre|',
    's:http|h:com|h:valjean|',
    's:http|h:com|h:marguerite|',
    's:http|h:com|h:mmeder|',
    's:http|h:com|h:isabeau|',
    's:http|h:com|h:gervais|',
    's:http|h:com|h:tholomyes|',
    's:http|h:com|h:listolier|',
    's:http|h:com|h:fameuil|',
    's:http|h:com|h:blacheville|',
    's:http|h:com|h:favourite|',
    's:http|h:com|h:dahlia|',
    's:http|h:com|h:zephine|',
    's:http|h:com|h:fantine|',
    's:http|h:com|h:mmethenardier|',
    's:http|h:com|h:thenardier|',
    's:http|h:com|h:cosette|',
    's:http|h:com|h:javert|',
    's:http|h:com|h:fauchelevent|',
    's:http|h:com|h:bamatabois|',
    's:http|h:com|h:perpetue|',
    's:http|h:com|h:simplice|',
    's:http|h:com|h:scaufflaire|',
    's:http|h:com|h:woman1|',
    's:http|h:com|h:judge|',
    's:http|h:com|h:champmathieu|',
    's:http|h:com|h:brevet|',
    's:http|h:com|h:chenildieu|',
    's:http|h:com|h:cochepaille|',
    's:http|h:com|h:pontmercy|',
    's:http|h:com|h:boulatruelle|',
    's:http|h:com|h:eponine|',
    's:http|h:com|h:anzelma|',
    's:http|h:com|h:woman2|',
    's:http|h:com|h:motherinnocent|',
    's:http|h:com|h:gribier|',
    's:http|h:com|h:jondrette|',
    's:http|h:com|h:mmeburgon|',
    's:http|h:com|h:gavroche|',
    's:http|h:com|h:gillenormand|',
    's:http|h:com|h:magnon|',
    's:http|h:com|h:mllegillenormand|',
    's:http|h:com|h:mmepontmercy|',
    's:http|h:com|h:mllevaubois|',
    's:http|h:com|h:ltgillenormand|',
    's:http|h:com|h:marius|',
    's:http|h:com|h:baronesst|',
    's:http|h:com|h:mabeuf|',
    's:http|h:com|h:enjolras|',
    's:http|h:com|h:combeferre|',
    's:http|h:com|h:prouvaire|',
    's:http|h:com|h:feuilly|',
    's:http|h:com|h:courfeyrac|',
    's:http|h:com|h:bahorel|',
    's:http|h:com|h:bossuet|',
    's:http|h:com|h:joly|',
    's:http|h:com|h:grantaire|',
    's:http|h:com|h:motherplutarch|',
    's:http|h:com|h:gueulemer|',
    's:http|h:com|h:babet|',
    's:http|h:com|h:claquesous|',
    's:http|h:com|h:montparnasse|',
    's:http|h:com|h:toussaint|',
    's:http|h:com|h:child1|',
    's:http|h:com|h:child2|',
    's:http|h:com|h:brujon|',
    's:http|h:com|h:mmehucheloup|'
]

LINKS = [
    ('s:http|h:com|h:napoleon|', 's:http|h:com|h:myriel|'),
    ('s:http|h:com|h:mllebaptistine|', 's:http|h:com|h:myriel|'),
    ('s:http|h:com|h:mmemagloire|', 's:http|h:com|h:myriel|'),
    ('s:http|h:com|h:mmemagloire|', 's:http|h:com|h:mllebaptistine|'),
    ('s:http|h:com|h:countessdelo|', 's:http|h:com|h:myriel|'),
    ('s:http|h:com|h:geborand|', 's:http|h:com|h:myriel|'),
    ('s:http|h:com|h:champtercier|', 's:http|h:com|h:myriel|'),
    ('s:http|h:com|h:cravatte|', 's:http|h:com|h:myriel|'),
    ('s:http|h:com|h:count|', 's:http|h:com|h:myriel|'),
    ('s:http|h:com|h:oldman|', 's:http|h:com|h:myriel|'),
    ('s:http|h:com|h:valjean|', 's:http|h:com|h:myriel|'),
    ('s:http|h:com|h:valjean|', 's:http|h:com|h:mllebaptistine|'),
    ('s:http|h:com|h:valjean|', 's:http|h:com|h:mmemagloire|'),
    ('s:http|h:com|h:valjean|', 's:http|h:com|h:labarre|'),
    ('s:http|h:com|h:marguerite|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:mmeder|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:isabeau|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:gervais|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:listolier|', 's:http|h:com|h:tholomyes|'),
    ('s:http|h:com|h:fameuil|', 's:http|h:com|h:tholomyes|'),
    ('s:http|h:com|h:fameuil|', 's:http|h:com|h:listolier|'),
    ('s:http|h:com|h:blacheville|', 's:http|h:com|h:tholomyes|'),
    ('s:http|h:com|h:blacheville|', 's:http|h:com|h:listolier|'),
    ('s:http|h:com|h:blacheville|', 's:http|h:com|h:fameuil|'),
    ('s:http|h:com|h:favourite|', 's:http|h:com|h:tholomyes|'),
    ('s:http|h:com|h:favourite|', 's:http|h:com|h:listolier|'),
    ('s:http|h:com|h:favourite|', 's:http|h:com|h:fameuil|'),
    ('s:http|h:com|h:favourite|', 's:http|h:com|h:blacheville|'),
    ('s:http|h:com|h:dahlia|', 's:http|h:com|h:tholomyes|'),
    ('s:http|h:com|h:dahlia|', 's:http|h:com|h:listolier|'),
    ('s:http|h:com|h:dahlia|', 's:http|h:com|h:fameuil|'),
    ('s:http|h:com|h:dahlia|', 's:http|h:com|h:blacheville|'),
    ('s:http|h:com|h:dahlia|', 's:http|h:com|h:favourite|'),
    ('s:http|h:com|h:zephine|', 's:http|h:com|h:tholomyes|'),
    ('s:http|h:com|h:zephine|', 's:http|h:com|h:listolier|'),
    ('s:http|h:com|h:zephine|', 's:http|h:com|h:fameuil|'),
    ('s:http|h:com|h:zephine|', 's:http|h:com|h:blacheville|'),
    ('s:http|h:com|h:zephine|', 's:http|h:com|h:favourite|'),
    ('s:http|h:com|h:zephine|', 's:http|h:com|h:dahlia|'),
    ('s:http|h:com|h:fantine|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:fantine|', 's:http|h:com|h:marguerite|'),
    ('s:http|h:com|h:fantine|', 's:http|h:com|h:tholomyes|'),
    ('s:http|h:com|h:fantine|', 's:http|h:com|h:listolier|'),
    ('s:http|h:com|h:fantine|', 's:http|h:com|h:fameuil|'),
    ('s:http|h:com|h:fantine|', 's:http|h:com|h:blacheville|'),
    ('s:http|h:com|h:fantine|', 's:http|h:com|h:favourite|'),
    ('s:http|h:com|h:fantine|', 's:http|h:com|h:dahlia|'),
    ('s:http|h:com|h:fantine|', 's:http|h:com|h:zephine|'),
    ('s:http|h:com|h:mmethenardier|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:mmethenardier|', 's:http|h:com|h:fantine|'),
    ('s:http|h:com|h:thenardier|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:thenardier|', 's:http|h:com|h:fantine|'),
    ('s:http|h:com|h:thenardier|', 's:http|h:com|h:mmethenardier|'),
    ('s:http|h:com|h:cosette|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:cosette|', 's:http|h:com|h:tholomyes|'),
    ('s:http|h:com|h:cosette|', 's:http|h:com|h:mmethenardier|'),
    ('s:http|h:com|h:cosette|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:javert|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:javert|', 's:http|h:com|h:fantine|'),
    ('s:http|h:com|h:javert|', 's:http|h:com|h:mmethenardier|'),
    ('s:http|h:com|h:javert|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:javert|', 's:http|h:com|h:cosette|'),
    ('s:http|h:com|h:fauchelevent|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:fauchelevent|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:bamatabois|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:bamatabois|', 's:http|h:com|h:fantine|'),
    ('s:http|h:com|h:bamatabois|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:perpetue|', 's:http|h:com|h:fantine|'),
    ('s:http|h:com|h:simplice|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:simplice|', 's:http|h:com|h:fantine|'),
    ('s:http|h:com|h:simplice|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:simplice|', 's:http|h:com|h:perpetue|'),
    ('s:http|h:com|h:scaufflaire|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:woman1|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:woman1|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:judge|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:judge|', 's:http|h:com|h:bamatabois|'),
    ('s:http|h:com|h:champmathieu|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:champmathieu|', 's:http|h:com|h:bamatabois|'),
    ('s:http|h:com|h:champmathieu|', 's:http|h:com|h:judge|'),
    ('s:http|h:com|h:brevet|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:brevet|', 's:http|h:com|h:bamatabois|'),
    ('s:http|h:com|h:brevet|', 's:http|h:com|h:judge|'),
    ('s:http|h:com|h:brevet|', 's:http|h:com|h:champmathieu|'),
    ('s:http|h:com|h:chenildieu|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:chenildieu|', 's:http|h:com|h:bamatabois|'),
    ('s:http|h:com|h:chenildieu|', 's:http|h:com|h:judge|'),
    ('s:http|h:com|h:chenildieu|', 's:http|h:com|h:champmathieu|'),
    ('s:http|h:com|h:chenildieu|', 's:http|h:com|h:brevet|'),
    ('s:http|h:com|h:cochepaille|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:cochepaille|', 's:http|h:com|h:bamatabois|'),
    ('s:http|h:com|h:cochepaille|', 's:http|h:com|h:judge|'),
    ('s:http|h:com|h:cochepaille|', 's:http|h:com|h:champmathieu|'),
    ('s:http|h:com|h:cochepaille|', 's:http|h:com|h:brevet|'),
    ('s:http|h:com|h:cochepaille|', 's:http|h:com|h:chenildieu|'),
    ('s:http|h:com|h:pontmercy|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:boulatruelle|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:eponine|', 's:http|h:com|h:mmethenardier|'),
    ('s:http|h:com|h:eponine|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:anzelma|', 's:http|h:com|h:mmethenardier|'),
    ('s:http|h:com|h:anzelma|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:anzelma|', 's:http|h:com|h:eponine|'),
    ('s:http|h:com|h:woman2|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:woman2|', 's:http|h:com|h:cosette|'),
    ('s:http|h:com|h:woman2|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:motherinnocent|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:motherinnocent|', 's:http|h:com|h:fauchelevent|'),
    ('s:http|h:com|h:gribier|', 's:http|h:com|h:fauchelevent|'),
    ('s:http|h:com|h:mmeburgon|', 's:http|h:com|h:jondrette|'),
    ('s:http|h:com|h:gavroche|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:gavroche|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:gavroche|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:gavroche|', 's:http|h:com|h:mmeburgon|'),
    ('s:http|h:com|h:gillenormand|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:gillenormand|', 's:http|h:com|h:cosette|'),
    ('s:http|h:com|h:magnon|', 's:http|h:com|h:mmethenardier|'),
    ('s:http|h:com|h:magnon|', 's:http|h:com|h:gillenormand|'),
    ('s:http|h:com|h:mllegillenormand|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:mllegillenormand|', 's:http|h:com|h:cosette|'),
    ('s:http|h:com|h:mllegillenormand|', 's:http|h:com|h:gillenormand|'),
    ('s:http|h:com|h:mmepontmercy|', 's:http|h:com|h:pontmercy|'),
    ('s:http|h:com|h:mmepontmercy|', 's:http|h:com|h:mllegillenormand|'),
    ('s:http|h:com|h:mllevaubois|', 's:http|h:com|h:mllegillenormand|'),
    ('s:http|h:com|h:ltgillenormand|', 's:http|h:com|h:cosette|'),
    ('s:http|h:com|h:ltgillenormand|', 's:http|h:com|h:gillenormand|'),
    ('s:http|h:com|h:ltgillenormand|', 's:http|h:com|h:mllegillenormand|'),
    ('s:http|h:com|h:marius|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:marius|', 's:http|h:com|h:tholomyes|'),
    ('s:http|h:com|h:marius|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:marius|', 's:http|h:com|h:cosette|'),
    ('s:http|h:com|h:marius|', 's:http|h:com|h:pontmercy|'),
    ('s:http|h:com|h:marius|', 's:http|h:com|h:eponine|'),
    ('s:http|h:com|h:marius|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:marius|', 's:http|h:com|h:gillenormand|'),
    ('s:http|h:com|h:marius|', 's:http|h:com|h:mllegillenormand|'),
    ('s:http|h:com|h:marius|', 's:http|h:com|h:ltgillenormand|'),
    ('s:http|h:com|h:baronesst|', 's:http|h:com|h:gillenormand|'),
    ('s:http|h:com|h:baronesst|', 's:http|h:com|h:marius|'),
    ('s:http|h:com|h:mabeuf|', 's:http|h:com|h:eponine|'),
    ('s:http|h:com|h:mabeuf|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:mabeuf|', 's:http|h:com|h:marius|'),
    ('s:http|h:com|h:enjolras|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:enjolras|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:enjolras|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:enjolras|', 's:http|h:com|h:marius|'),
    ('s:http|h:com|h:enjolras|', 's:http|h:com|h:mabeuf|'),
    ('s:http|h:com|h:combeferre|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:combeferre|', 's:http|h:com|h:marius|'),
    ('s:http|h:com|h:combeferre|', 's:http|h:com|h:mabeuf|'),
    ('s:http|h:com|h:combeferre|', 's:http|h:com|h:enjolras|'),
    ('s:http|h:com|h:prouvaire|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:prouvaire|', 's:http|h:com|h:enjolras|'),
    ('s:http|h:com|h:prouvaire|', 's:http|h:com|h:combeferre|'),
    ('s:http|h:com|h:feuilly|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:feuilly|', 's:http|h:com|h:marius|'),
    ('s:http|h:com|h:feuilly|', 's:http|h:com|h:mabeuf|'),
    ('s:http|h:com|h:feuilly|', 's:http|h:com|h:enjolras|'),
    ('s:http|h:com|h:feuilly|', 's:http|h:com|h:combeferre|'),
    ('s:http|h:com|h:feuilly|', 's:http|h:com|h:prouvaire|'),
    ('s:http|h:com|h:courfeyrac|', 's:http|h:com|h:eponine|'),
    ('s:http|h:com|h:courfeyrac|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:courfeyrac|', 's:http|h:com|h:marius|'),
    ('s:http|h:com|h:courfeyrac|', 's:http|h:com|h:mabeuf|'),
    ('s:http|h:com|h:courfeyrac|', 's:http|h:com|h:enjolras|'),
    ('s:http|h:com|h:courfeyrac|', 's:http|h:com|h:combeferre|'),
    ('s:http|h:com|h:courfeyrac|', 's:http|h:com|h:prouvaire|'),
    ('s:http|h:com|h:courfeyrac|', 's:http|h:com|h:feuilly|'),
    ('s:http|h:com|h:bahorel|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:bahorel|', 's:http|h:com|h:marius|'),
    ('s:http|h:com|h:bahorel|', 's:http|h:com|h:mabeuf|'),
    ('s:http|h:com|h:bahorel|', 's:http|h:com|h:enjolras|'),
    ('s:http|h:com|h:bahorel|', 's:http|h:com|h:combeferre|'),
    ('s:http|h:com|h:bahorel|', 's:http|h:com|h:prouvaire|'),
    ('s:http|h:com|h:bahorel|', 's:http|h:com|h:feuilly|'),
    ('s:http|h:com|h:bahorel|', 's:http|h:com|h:courfeyrac|'),
    ('s:http|h:com|h:bossuet|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:bossuet|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:bossuet|', 's:http|h:com|h:marius|'),
    ('s:http|h:com|h:bossuet|', 's:http|h:com|h:mabeuf|'),
    ('s:http|h:com|h:bossuet|', 's:http|h:com|h:enjolras|'),
    ('s:http|h:com|h:bossuet|', 's:http|h:com|h:combeferre|'),
    ('s:http|h:com|h:bossuet|', 's:http|h:com|h:prouvaire|'),
    ('s:http|h:com|h:bossuet|', 's:http|h:com|h:feuilly|'),
    ('s:http|h:com|h:bossuet|', 's:http|h:com|h:courfeyrac|'),
    ('s:http|h:com|h:bossuet|', 's:http|h:com|h:bahorel|'),
    ('s:http|h:com|h:joly|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:joly|', 's:http|h:com|h:marius|'),
    ('s:http|h:com|h:joly|', 's:http|h:com|h:mabeuf|'),
    ('s:http|h:com|h:joly|', 's:http|h:com|h:enjolras|'),
    ('s:http|h:com|h:joly|', 's:http|h:com|h:combeferre|'),
    ('s:http|h:com|h:joly|', 's:http|h:com|h:prouvaire|'),
    ('s:http|h:com|h:joly|', 's:http|h:com|h:feuilly|'),
    ('s:http|h:com|h:joly|', 's:http|h:com|h:courfeyrac|'),
    ('s:http|h:com|h:joly|', 's:http|h:com|h:bahorel|'),
    ('s:http|h:com|h:joly|', 's:http|h:com|h:bossuet|'),
    ('s:http|h:com|h:grantaire|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:grantaire|', 's:http|h:com|h:enjolras|'),
    ('s:http|h:com|h:grantaire|', 's:http|h:com|h:combeferre|'),
    ('s:http|h:com|h:grantaire|', 's:http|h:com|h:prouvaire|'),
    ('s:http|h:com|h:grantaire|', 's:http|h:com|h:feuilly|'),
    ('s:http|h:com|h:grantaire|', 's:http|h:com|h:courfeyrac|'),
    ('s:http|h:com|h:grantaire|', 's:http|h:com|h:bahorel|'),
    ('s:http|h:com|h:grantaire|', 's:http|h:com|h:bossuet|'),
    ('s:http|h:com|h:grantaire|', 's:http|h:com|h:joly|'),
    ('s:http|h:com|h:motherplutarch|', 's:http|h:com|h:mabeuf|'),
    ('s:http|h:com|h:gueulemer|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:gueulemer|', 's:http|h:com|h:mmethenardier|'),
    ('s:http|h:com|h:gueulemer|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:gueulemer|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:gueulemer|', 's:http|h:com|h:eponine|'),
    ('s:http|h:com|h:gueulemer|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:babet|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:babet|', 's:http|h:com|h:mmethenardier|'),
    ('s:http|h:com|h:babet|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:babet|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:babet|', 's:http|h:com|h:eponine|'),
    ('s:http|h:com|h:babet|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:babet|', 's:http|h:com|h:gueulemer|'),
    ('s:http|h:com|h:claquesous|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:claquesous|', 's:http|h:com|h:mmethenardier|'),
    ('s:http|h:com|h:claquesous|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:claquesous|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:claquesous|', 's:http|h:com|h:eponine|'),
    ('s:http|h:com|h:claquesous|', 's:http|h:com|h:enjolras|'),
    ('s:http|h:com|h:claquesous|', 's:http|h:com|h:gueulemer|'),
    ('s:http|h:com|h:claquesous|', 's:http|h:com|h:babet|'),
    ('s:http|h:com|h:montparnasse|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:montparnasse|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:montparnasse|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:montparnasse|', 's:http|h:com|h:eponine|'),
    ('s:http|h:com|h:montparnasse|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:montparnasse|', 's:http|h:com|h:gueulemer|'),
    ('s:http|h:com|h:montparnasse|', 's:http|h:com|h:babet|'),
    ('s:http|h:com|h:montparnasse|', 's:http|h:com|h:claquesous|'),
    ('s:http|h:com|h:toussaint|', 's:http|h:com|h:valjean|'),
    ('s:http|h:com|h:toussaint|', 's:http|h:com|h:cosette|'),
    ('s:http|h:com|h:toussaint|', 's:http|h:com|h:javert|'),
    ('s:http|h:com|h:child1|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:child2|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:child2|', 's:http|h:com|h:child1|'),
    ('s:http|h:com|h:brujon|', 's:http|h:com|h:thenardier|'),
    ('s:http|h:com|h:brujon|', 's:http|h:com|h:eponine|'),
    ('s:http|h:com|h:brujon|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:brujon|', 's:http|h:com|h:gueulemer|'),
    ('s:http|h:com|h:brujon|', 's:http|h:com|h:babet|'),
    ('s:http|h:com|h:brujon|', 's:http|h:com|h:claquesous|'),
    ('s:http|h:com|h:brujon|', 's:http|h:com|h:montparnasse|'),
    ('s:http|h:com|h:mmehucheloup|', 's:http|h:com|h:gavroche|'),
    ('s:http|h:com|h:mmehucheloup|', 's:http|h:com|h:enjolras|'),
    ('s:http|h:com|h:mmehucheloup|', 's:http|h:com|h:courfeyrac|'),
    ('s:http|h:com|h:mmehucheloup|', 's:http|h:com|h:bahorel|'),
    ('s:http|h:com|h:mmehucheloup|', 's:http|h:com|h:bossuet|'),
    ('s:http|h:com|h:mmehucheloup|', 's:http|h:com|h:joly|'),
    ('s:http|h:com|h:mmehucheloup|', 's:http|h:com|h:grantaire|')
]


class TestHugoLinks(TraphTestCase):

    def test_hugo_links(self):
        traph = self.get_traph()

        # Indexing data
        data = defaultdict(list)

        for source, target in LINKS:
            data[source].append(target)

        report = traph.index_batch_crawl(data)
        webentities = report.created_webentities

        # Checking pages
        pages_in_traph = set(lru for _, lru in traph.pages_iter())
        self.assertEqual(pages_in_traph, set(PAGES))

        # Checking links
        links_in_traph = set(traph.links_iter())
        self.assertEqual(links_in_traph, set(LINKS))

        traph.close()
