# -*- coding: utf-8 -*-
# =============================================================================
# Hugo Links Unit Tests
# =============================================================================
#
# Testing links using the famous "Les Misérables" network example.
#
from collections import defaultdict
from test.test_cases import TraphTestCase

PAGES = [
    b's:http|h:com|h:myriel|',
    b's:http|h:com|h:napoleon|',
    b's:http|h:com|h:mllebaptistine|',
    b's:http|h:com|h:mmemagloire|',
    b's:http|h:com|h:countessdelo|',
    b's:http|h:com|h:geborand|',
    b's:http|h:com|h:champtercier|',
    b's:http|h:com|h:cravatte|',
    b's:http|h:com|h:count|',
    b's:http|h:com|h:oldman|',
    b's:http|h:com|h:labarre|',
    b's:http|h:com|h:valjean|',
    b's:http|h:com|h:marguerite|',
    b's:http|h:com|h:mmeder|',
    b's:http|h:com|h:isabeau|',
    b's:http|h:com|h:gervais|',
    b's:http|h:com|h:tholomyes|',
    b's:http|h:com|h:listolier|',
    b's:http|h:com|h:fameuil|',
    b's:http|h:com|h:blacheville|',
    b's:http|h:com|h:favourite|',
    b's:http|h:com|h:dahlia|',
    b's:http|h:com|h:zephine|',
    b's:http|h:com|h:fantine|',
    b's:http|h:com|h:mmethenardier|',
    b's:http|h:com|h:thenardier|',
    b's:http|h:com|h:cosette|',
    b's:http|h:com|h:javert|',
    b's:http|h:com|h:fauchelevent|',
    b's:http|h:com|h:bamatabois|',
    b's:http|h:com|h:perpetue|',
    b's:http|h:com|h:simplice|',
    b's:http|h:com|h:scaufflaire|',
    b's:http|h:com|h:woman1|',
    b's:http|h:com|h:judge|',
    b's:http|h:com|h:champmathieu|',
    b's:http|h:com|h:brevet|',
    b's:http|h:com|h:chenildieu|',
    b's:http|h:com|h:cochepaille|',
    b's:http|h:com|h:pontmercy|',
    b's:http|h:com|h:boulatruelle|',
    b's:http|h:com|h:eponine|',
    b's:http|h:com|h:anzelma|',
    b's:http|h:com|h:woman2|',
    b's:http|h:com|h:motherinnocent|',
    b's:http|h:com|h:gribier|',
    b's:http|h:com|h:jondrette|',
    b's:http|h:com|h:mmeburgon|',
    b's:http|h:com|h:gavroche|',
    b's:http|h:com|h:gillenormand|',
    b's:http|h:com|h:magnon|',
    b's:http|h:com|h:mllegillenormand|',
    b's:http|h:com|h:mmepontmercy|',
    b's:http|h:com|h:mllevaubois|',
    b's:http|h:com|h:ltgillenormand|',
    b's:http|h:com|h:marius|',
    b's:http|h:com|h:baronesst|',
    b's:http|h:com|h:mabeuf|',
    b's:http|h:com|h:enjolras|',
    b's:http|h:com|h:combeferre|',
    b's:http|h:com|h:prouvaire|',
    b's:http|h:com|h:feuilly|',
    b's:http|h:com|h:courfeyrac|',
    b's:http|h:com|h:bahorel|',
    b's:http|h:com|h:bossuet|',
    b's:http|h:com|h:joly|',
    b's:http|h:com|h:grantaire|',
    b's:http|h:com|h:motherplutarch|',
    b's:http|h:com|h:gueulemer|',
    b's:http|h:com|h:babet|',
    b's:http|h:com|h:claquesous|',
    b's:http|h:com|h:montparnasse|',
    b's:http|h:com|h:toussaint|',
    b's:http|h:com|h:child1|',
    b's:http|h:com|h:child2|',
    b's:http|h:com|h:brujon|',
    b's:http|h:com|h:mmehucheloup|'
]

LINKS = [
    (b's:http|h:com|h:napoleon|', b's:http|h:com|h:myriel|'),
    (b's:http|h:com|h:mllebaptistine|', b's:http|h:com|h:myriel|'),
    (b's:http|h:com|h:mmemagloire|', b's:http|h:com|h:myriel|'),
    (b's:http|h:com|h:mmemagloire|', b's:http|h:com|h:mllebaptistine|'),
    (b's:http|h:com|h:countessdelo|', b's:http|h:com|h:myriel|'),
    (b's:http|h:com|h:geborand|', b's:http|h:com|h:myriel|'),
    (b's:http|h:com|h:champtercier|', b's:http|h:com|h:myriel|'),
    (b's:http|h:com|h:cravatte|', b's:http|h:com|h:myriel|'),
    (b's:http|h:com|h:count|', b's:http|h:com|h:myriel|'),
    (b's:http|h:com|h:oldman|', b's:http|h:com|h:myriel|'),
    (b's:http|h:com|h:valjean|', b's:http|h:com|h:myriel|'),
    (b's:http|h:com|h:valjean|', b's:http|h:com|h:mllebaptistine|'),
    (b's:http|h:com|h:valjean|', b's:http|h:com|h:mmemagloire|'),
    (b's:http|h:com|h:valjean|', b's:http|h:com|h:labarre|'),
    (b's:http|h:com|h:marguerite|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:mmeder|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:isabeau|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:gervais|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:listolier|', b's:http|h:com|h:tholomyes|'),
    (b's:http|h:com|h:fameuil|', b's:http|h:com|h:tholomyes|'),
    (b's:http|h:com|h:fameuil|', b's:http|h:com|h:listolier|'),
    (b's:http|h:com|h:blacheville|', b's:http|h:com|h:tholomyes|'),
    (b's:http|h:com|h:blacheville|', b's:http|h:com|h:listolier|'),
    (b's:http|h:com|h:blacheville|', b's:http|h:com|h:fameuil|'),
    (b's:http|h:com|h:favourite|', b's:http|h:com|h:tholomyes|'),
    (b's:http|h:com|h:favourite|', b's:http|h:com|h:listolier|'),
    (b's:http|h:com|h:favourite|', b's:http|h:com|h:fameuil|'),
    (b's:http|h:com|h:favourite|', b's:http|h:com|h:blacheville|'),
    (b's:http|h:com|h:dahlia|', b's:http|h:com|h:tholomyes|'),
    (b's:http|h:com|h:dahlia|', b's:http|h:com|h:listolier|'),
    (b's:http|h:com|h:dahlia|', b's:http|h:com|h:fameuil|'),
    (b's:http|h:com|h:dahlia|', b's:http|h:com|h:blacheville|'),
    (b's:http|h:com|h:dahlia|', b's:http|h:com|h:favourite|'),
    (b's:http|h:com|h:zephine|', b's:http|h:com|h:tholomyes|'),
    (b's:http|h:com|h:zephine|', b's:http|h:com|h:listolier|'),
    (b's:http|h:com|h:zephine|', b's:http|h:com|h:fameuil|'),
    (b's:http|h:com|h:zephine|', b's:http|h:com|h:blacheville|'),
    (b's:http|h:com|h:zephine|', b's:http|h:com|h:favourite|'),
    (b's:http|h:com|h:zephine|', b's:http|h:com|h:dahlia|'),
    (b's:http|h:com|h:fantine|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:fantine|', b's:http|h:com|h:marguerite|'),
    (b's:http|h:com|h:fantine|', b's:http|h:com|h:tholomyes|'),
    (b's:http|h:com|h:fantine|', b's:http|h:com|h:listolier|'),
    (b's:http|h:com|h:fantine|', b's:http|h:com|h:fameuil|'),
    (b's:http|h:com|h:fantine|', b's:http|h:com|h:blacheville|'),
    (b's:http|h:com|h:fantine|', b's:http|h:com|h:favourite|'),
    (b's:http|h:com|h:fantine|', b's:http|h:com|h:dahlia|'),
    (b's:http|h:com|h:fantine|', b's:http|h:com|h:zephine|'),
    (b's:http|h:com|h:mmethenardier|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:mmethenardier|', b's:http|h:com|h:fantine|'),
    (b's:http|h:com|h:thenardier|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:thenardier|', b's:http|h:com|h:fantine|'),
    (b's:http|h:com|h:thenardier|', b's:http|h:com|h:mmethenardier|'),
    (b's:http|h:com|h:cosette|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:cosette|', b's:http|h:com|h:tholomyes|'),
    (b's:http|h:com|h:cosette|', b's:http|h:com|h:mmethenardier|'),
    (b's:http|h:com|h:cosette|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:javert|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:javert|', b's:http|h:com|h:fantine|'),
    (b's:http|h:com|h:javert|', b's:http|h:com|h:mmethenardier|'),
    (b's:http|h:com|h:javert|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:javert|', b's:http|h:com|h:cosette|'),
    (b's:http|h:com|h:fauchelevent|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:fauchelevent|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:bamatabois|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:bamatabois|', b's:http|h:com|h:fantine|'),
    (b's:http|h:com|h:bamatabois|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:perpetue|', b's:http|h:com|h:fantine|'),
    (b's:http|h:com|h:simplice|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:simplice|', b's:http|h:com|h:fantine|'),
    (b's:http|h:com|h:simplice|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:simplice|', b's:http|h:com|h:perpetue|'),
    (b's:http|h:com|h:scaufflaire|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:woman1|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:woman1|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:judge|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:judge|', b's:http|h:com|h:bamatabois|'),
    (b's:http|h:com|h:champmathieu|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:champmathieu|', b's:http|h:com|h:bamatabois|'),
    (b's:http|h:com|h:champmathieu|', b's:http|h:com|h:judge|'),
    (b's:http|h:com|h:brevet|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:brevet|', b's:http|h:com|h:bamatabois|'),
    (b's:http|h:com|h:brevet|', b's:http|h:com|h:judge|'),
    (b's:http|h:com|h:brevet|', b's:http|h:com|h:champmathieu|'),
    (b's:http|h:com|h:chenildieu|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:chenildieu|', b's:http|h:com|h:bamatabois|'),
    (b's:http|h:com|h:chenildieu|', b's:http|h:com|h:judge|'),
    (b's:http|h:com|h:chenildieu|', b's:http|h:com|h:champmathieu|'),
    (b's:http|h:com|h:chenildieu|', b's:http|h:com|h:brevet|'),
    (b's:http|h:com|h:cochepaille|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:cochepaille|', b's:http|h:com|h:bamatabois|'),
    (b's:http|h:com|h:cochepaille|', b's:http|h:com|h:judge|'),
    (b's:http|h:com|h:cochepaille|', b's:http|h:com|h:champmathieu|'),
    (b's:http|h:com|h:cochepaille|', b's:http|h:com|h:brevet|'),
    (b's:http|h:com|h:cochepaille|', b's:http|h:com|h:chenildieu|'),
    (b's:http|h:com|h:pontmercy|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:boulatruelle|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:eponine|', b's:http|h:com|h:mmethenardier|'),
    (b's:http|h:com|h:eponine|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:anzelma|', b's:http|h:com|h:mmethenardier|'),
    (b's:http|h:com|h:anzelma|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:anzelma|', b's:http|h:com|h:eponine|'),
    (b's:http|h:com|h:woman2|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:woman2|', b's:http|h:com|h:cosette|'),
    (b's:http|h:com|h:woman2|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:motherinnocent|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:motherinnocent|', b's:http|h:com|h:fauchelevent|'),
    (b's:http|h:com|h:gribier|', b's:http|h:com|h:fauchelevent|'),
    (b's:http|h:com|h:mmeburgon|', b's:http|h:com|h:jondrette|'),
    (b's:http|h:com|h:gavroche|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:gavroche|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:gavroche|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:gavroche|', b's:http|h:com|h:mmeburgon|'),
    (b's:http|h:com|h:gillenormand|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:gillenormand|', b's:http|h:com|h:cosette|'),
    (b's:http|h:com|h:magnon|', b's:http|h:com|h:mmethenardier|'),
    (b's:http|h:com|h:magnon|', b's:http|h:com|h:gillenormand|'),
    (b's:http|h:com|h:mllegillenormand|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:mllegillenormand|', b's:http|h:com|h:cosette|'),
    (b's:http|h:com|h:mllegillenormand|', b's:http|h:com|h:gillenormand|'),
    (b's:http|h:com|h:mmepontmercy|', b's:http|h:com|h:pontmercy|'),
    (b's:http|h:com|h:mmepontmercy|', b's:http|h:com|h:mllegillenormand|'),
    (b's:http|h:com|h:mllevaubois|', b's:http|h:com|h:mllegillenormand|'),
    (b's:http|h:com|h:ltgillenormand|', b's:http|h:com|h:cosette|'),
    (b's:http|h:com|h:ltgillenormand|', b's:http|h:com|h:gillenormand|'),
    (b's:http|h:com|h:ltgillenormand|', b's:http|h:com|h:mllegillenormand|'),
    (b's:http|h:com|h:marius|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:marius|', b's:http|h:com|h:tholomyes|'),
    (b's:http|h:com|h:marius|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:marius|', b's:http|h:com|h:cosette|'),
    (b's:http|h:com|h:marius|', b's:http|h:com|h:pontmercy|'),
    (b's:http|h:com|h:marius|', b's:http|h:com|h:eponine|'),
    (b's:http|h:com|h:marius|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:marius|', b's:http|h:com|h:gillenormand|'),
    (b's:http|h:com|h:marius|', b's:http|h:com|h:mllegillenormand|'),
    (b's:http|h:com|h:marius|', b's:http|h:com|h:ltgillenormand|'),
    (b's:http|h:com|h:baronesst|', b's:http|h:com|h:gillenormand|'),
    (b's:http|h:com|h:baronesst|', b's:http|h:com|h:marius|'),
    (b's:http|h:com|h:mabeuf|', b's:http|h:com|h:eponine|'),
    (b's:http|h:com|h:mabeuf|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:mabeuf|', b's:http|h:com|h:marius|'),
    (b's:http|h:com|h:enjolras|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:enjolras|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:enjolras|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:enjolras|', b's:http|h:com|h:marius|'),
    (b's:http|h:com|h:enjolras|', b's:http|h:com|h:mabeuf|'),
    (b's:http|h:com|h:combeferre|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:combeferre|', b's:http|h:com|h:marius|'),
    (b's:http|h:com|h:combeferre|', b's:http|h:com|h:mabeuf|'),
    (b's:http|h:com|h:combeferre|', b's:http|h:com|h:enjolras|'),
    (b's:http|h:com|h:prouvaire|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:prouvaire|', b's:http|h:com|h:enjolras|'),
    (b's:http|h:com|h:prouvaire|', b's:http|h:com|h:combeferre|'),
    (b's:http|h:com|h:feuilly|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:feuilly|', b's:http|h:com|h:marius|'),
    (b's:http|h:com|h:feuilly|', b's:http|h:com|h:mabeuf|'),
    (b's:http|h:com|h:feuilly|', b's:http|h:com|h:enjolras|'),
    (b's:http|h:com|h:feuilly|', b's:http|h:com|h:combeferre|'),
    (b's:http|h:com|h:feuilly|', b's:http|h:com|h:prouvaire|'),
    (b's:http|h:com|h:courfeyrac|', b's:http|h:com|h:eponine|'),
    (b's:http|h:com|h:courfeyrac|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:courfeyrac|', b's:http|h:com|h:marius|'),
    (b's:http|h:com|h:courfeyrac|', b's:http|h:com|h:mabeuf|'),
    (b's:http|h:com|h:courfeyrac|', b's:http|h:com|h:enjolras|'),
    (b's:http|h:com|h:courfeyrac|', b's:http|h:com|h:combeferre|'),
    (b's:http|h:com|h:courfeyrac|', b's:http|h:com|h:prouvaire|'),
    (b's:http|h:com|h:courfeyrac|', b's:http|h:com|h:feuilly|'),
    (b's:http|h:com|h:bahorel|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:bahorel|', b's:http|h:com|h:marius|'),
    (b's:http|h:com|h:bahorel|', b's:http|h:com|h:mabeuf|'),
    (b's:http|h:com|h:bahorel|', b's:http|h:com|h:enjolras|'),
    (b's:http|h:com|h:bahorel|', b's:http|h:com|h:combeferre|'),
    (b's:http|h:com|h:bahorel|', b's:http|h:com|h:prouvaire|'),
    (b's:http|h:com|h:bahorel|', b's:http|h:com|h:feuilly|'),
    (b's:http|h:com|h:bahorel|', b's:http|h:com|h:courfeyrac|'),
    (b's:http|h:com|h:bossuet|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:bossuet|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:bossuet|', b's:http|h:com|h:marius|'),
    (b's:http|h:com|h:bossuet|', b's:http|h:com|h:mabeuf|'),
    (b's:http|h:com|h:bossuet|', b's:http|h:com|h:enjolras|'),
    (b's:http|h:com|h:bossuet|', b's:http|h:com|h:combeferre|'),
    (b's:http|h:com|h:bossuet|', b's:http|h:com|h:prouvaire|'),
    (b's:http|h:com|h:bossuet|', b's:http|h:com|h:feuilly|'),
    (b's:http|h:com|h:bossuet|', b's:http|h:com|h:courfeyrac|'),
    (b's:http|h:com|h:bossuet|', b's:http|h:com|h:bahorel|'),
    (b's:http|h:com|h:joly|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:joly|', b's:http|h:com|h:marius|'),
    (b's:http|h:com|h:joly|', b's:http|h:com|h:mabeuf|'),
    (b's:http|h:com|h:joly|', b's:http|h:com|h:enjolras|'),
    (b's:http|h:com|h:joly|', b's:http|h:com|h:combeferre|'),
    (b's:http|h:com|h:joly|', b's:http|h:com|h:prouvaire|'),
    (b's:http|h:com|h:joly|', b's:http|h:com|h:feuilly|'),
    (b's:http|h:com|h:joly|', b's:http|h:com|h:courfeyrac|'),
    (b's:http|h:com|h:joly|', b's:http|h:com|h:bahorel|'),
    (b's:http|h:com|h:joly|', b's:http|h:com|h:bossuet|'),
    (b's:http|h:com|h:grantaire|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:grantaire|', b's:http|h:com|h:enjolras|'),
    (b's:http|h:com|h:grantaire|', b's:http|h:com|h:combeferre|'),
    (b's:http|h:com|h:grantaire|', b's:http|h:com|h:prouvaire|'),
    (b's:http|h:com|h:grantaire|', b's:http|h:com|h:feuilly|'),
    (b's:http|h:com|h:grantaire|', b's:http|h:com|h:courfeyrac|'),
    (b's:http|h:com|h:grantaire|', b's:http|h:com|h:bahorel|'),
    (b's:http|h:com|h:grantaire|', b's:http|h:com|h:bossuet|'),
    (b's:http|h:com|h:grantaire|', b's:http|h:com|h:joly|'),
    (b's:http|h:com|h:motherplutarch|', b's:http|h:com|h:mabeuf|'),
    (b's:http|h:com|h:gueulemer|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:gueulemer|', b's:http|h:com|h:mmethenardier|'),
    (b's:http|h:com|h:gueulemer|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:gueulemer|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:gueulemer|', b's:http|h:com|h:eponine|'),
    (b's:http|h:com|h:gueulemer|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:babet|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:babet|', b's:http|h:com|h:mmethenardier|'),
    (b's:http|h:com|h:babet|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:babet|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:babet|', b's:http|h:com|h:eponine|'),
    (b's:http|h:com|h:babet|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:babet|', b's:http|h:com|h:gueulemer|'),
    (b's:http|h:com|h:claquesous|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:claquesous|', b's:http|h:com|h:mmethenardier|'),
    (b's:http|h:com|h:claquesous|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:claquesous|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:claquesous|', b's:http|h:com|h:eponine|'),
    (b's:http|h:com|h:claquesous|', b's:http|h:com|h:enjolras|'),
    (b's:http|h:com|h:claquesous|', b's:http|h:com|h:gueulemer|'),
    (b's:http|h:com|h:claquesous|', b's:http|h:com|h:babet|'),
    (b's:http|h:com|h:montparnasse|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:montparnasse|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:montparnasse|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:montparnasse|', b's:http|h:com|h:eponine|'),
    (b's:http|h:com|h:montparnasse|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:montparnasse|', b's:http|h:com|h:gueulemer|'),
    (b's:http|h:com|h:montparnasse|', b's:http|h:com|h:babet|'),
    (b's:http|h:com|h:montparnasse|', b's:http|h:com|h:claquesous|'),
    (b's:http|h:com|h:toussaint|', b's:http|h:com|h:valjean|'),
    (b's:http|h:com|h:toussaint|', b's:http|h:com|h:cosette|'),
    (b's:http|h:com|h:toussaint|', b's:http|h:com|h:javert|'),
    (b's:http|h:com|h:child1|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:child2|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:child2|', b's:http|h:com|h:child1|'),
    (b's:http|h:com|h:brujon|', b's:http|h:com|h:thenardier|'),
    (b's:http|h:com|h:brujon|', b's:http|h:com|h:eponine|'),
    (b's:http|h:com|h:brujon|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:brujon|', b's:http|h:com|h:gueulemer|'),
    (b's:http|h:com|h:brujon|', b's:http|h:com|h:babet|'),
    (b's:http|h:com|h:brujon|', b's:http|h:com|h:claquesous|'),
    (b's:http|h:com|h:brujon|', b's:http|h:com|h:montparnasse|'),
    (b's:http|h:com|h:mmehucheloup|', b's:http|h:com|h:gavroche|'),
    (b's:http|h:com|h:mmehucheloup|', b's:http|h:com|h:enjolras|'),
    (b's:http|h:com|h:mmehucheloup|', b's:http|h:com|h:courfeyrac|'),
    (b's:http|h:com|h:mmehucheloup|', b's:http|h:com|h:bahorel|'),
    (b's:http|h:com|h:mmehucheloup|', b's:http|h:com|h:bossuet|'),
    (b's:http|h:com|h:mmehucheloup|', b's:http|h:com|h:joly|'),
    (b's:http|h:com|h:mmehucheloup|', b's:http|h:com|h:grantaire|')
]


class TestHugoLinks(TraphTestCase):

    def test_hugo_links(self):
        traph = self.get_traph()

        # Indexing data
        data = defaultdict(list)

        for source, target in LINKS:
            data[source].append(target)

        report = traph.index_batch_crawl(data)
        webentities = report.created_webentities

        # Checking pages
        pages_in_traph = set(lru for _, lru in traph.pages_iter())
        self.assertEqual(pages_in_traph, set(PAGES))

        # Checking links
        links_in_traph = set(traph.links_iter())
        self.assertEqual(links_in_traph, set(LINKS))

        traph.close()
